### ISSUE TITLE
Index.md from continuous deployment repo is overwriting the main index.md

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#108]
Landing page content is getting overwritten by index.md from continuous deployment repo

ignore index.md in [content-sources.yaml](https://github.com/operate-first/operate-first.github.io/blob/master/content-sources.yaml)

**Comment by hemajv** [comment]
I modified the [content-source.yaml](https://github.com/operate-first/operate-first.github.io/blob/master/content-sources.yaml):
```
- name: continuous deployment docs
  gitSrc: https://github.com/operate-first/continuous-deployment.git
  dir: continuous-deployment/docs
  urlPrefix: cd
  ignore:
    - "index.md"
    - "**/README.md"
```
however, this still seems to overwrite the [landing page index.md](https://github.com/operate-first/operate-first.github.io/blob/master/content/index.md)

You can view this in my gh-pages (in my branch `fix-cd-index`) here: https://hemajv.github.io/operate-first.github.io/fix-cd-index/
