### ISSUE TITLE
Discuss structure of content directories in remote-repos

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#52]
Earlier in [issue](https://github.com/operate-first/operate-first.github.io/issues/16#issuecomment-713722463), we faced a build issue from files which were not meant for publication on the website. 

We need to determine whether having separate folder(s) within the remote repos for the files we are planning to include on the website is the way to go. 

ref: 
1. [comment](https://github.com/operate-first/operate-first.github.io/issues/38#issuecomment-713804474)
2. [comment](https://github.com/operate-first/continuous-deployment/pull/54#issuecomment-716694713)

**Comment by hemajv** [comment]
@oindrillac @cfchase would it be possible to have a nested structure of folders that could be included in the table of contents. For eg: if I want to structure something like:

```
Continuous Deployment
├── ArgoCD Operations
│   └── all docs related to argocd
├── Installation Guide
│   └── CRC
│      ├── all docs related to CRC
│   └── Quicklab
│      ├── all docs related to Quicklab
```

**Comment by durandom** [comment]
The documentation in the source repos (e.g. continous-deployment or categorical-data-encoding) should remain consumable on it's own (e.g markdown links between items) and it should not have a dependency on this outlet here (e.g. not contain any metadata required by the op1st website)
But it can add metadata, which then could be used by the op1st website (but it's not a requirement).

**Comment by durandom** [comment]
> would it be possible to have a nested structure of folders that could be included in the table of contents. 

I guess we would need to create a dynamic toc file like https://github.com/operate-first/operate-first.github.io/blob/master/toc-sources.yaml
How much effort would it be to parse a directory structure instead of a toc file?
Otherwise we can start with adding the structure explicitly.

**Comment by cfchase** [comment]
> Earlier in [issue](https://github.com/operate-first/operate-first.github.io/issues/16#issuecomment-713722463), we faced a build issue from files which were not meant for publication on the website.
> 
> We need to determine whether having separate folder(s) within the remote repos for the files we are planning to include on the website is the way to go.
> 
> ref:
> 
> 1. [comment](https://github.com/operate-first/operate-first.github.io/issues/38#issuecomment-713804474)
> 2. [comment](https://github.com/operate-first/continuous-deployment/pull/54#issuecomment-716694713)

I designed the content repos to work from anywhere, but I never really designed it so you can put all kinds of garbage in it.  I think some sort of structure and standards should apply or else you're going to break the build on a regular basis.

> @oindrillac @cfchase would it be possible to have a nested structure of folders that could be included in the table of contents. For eg: if I want to structure something like:
> 
> ```
> Continuous Deployment
> ├── ArgoCD Operations
> │   └── all docs related to argocd
> ├── Installation Guide
> │   └── CRC
> │      ├── all docs related to CRC
> │   └── Quicklab
> │      ├── all docs related to Quicklab
> ```

I don't think the left hand nav from patternfly supports 3 levels of expanding links, and it might be annoying to have to follow it down.  I think there might be other ways of solving this. Perhaps, for now, a single page with a on page table of contents with links to anchors on the page for CRC/Quicklab sections, would work?


> > would it be possible to have a nested structure of folders that could be included in the table of contents.
> 
> I guess we would need to create a dynamic toc file like https://github.com/operate-first/operate-first.github.io/blob/master/toc-sources.yaml
> How much effort would it be to parse a directory structure instead of a toc file?
> Otherwise we can start with adding the structure explicitly.

This is actually pretty easy, but we'd still have to have some metadata to specify the order of folders and the links inside them.  Having to do that anyway made me do the whole `toc.yaml` approach.

**Comment by hemajv** [comment]
> > would it be possible to have a nested structure of folders that could be included in the table of contents.
> 
> I guess we would need to create a dynamic toc file like https://github.com/operate-first/operate-first.github.io/blob/master/toc-sources.yaml
> How much effort would it be to parse a directory structure instead of a toc file?
> Otherwise we can start with adding the structure explicitly.

I did try to define the nested structuring in the toc file (https://github.com/operate-first/operate-first.github.io/blob/master/content/cd-toc.yaml) with something like:

```
- id: cd
  label: Continuous Deployment
    - id: argocd
      label: ArgoCD Operations
      links:
        - id: argocd-doc-1
          label: Create ArgoCD Application Manifest
          href: /cd-argocd/create_argocd_application_manifest
        - id: argocd-doc-2
          label: Get ArgoCD to Manage your app
          href: /cd-argocd/get_argocd_to_manage_your_app
    - id: ig
      label: Installation Guides
        - id: crc
          label: crc
          links:
            - id: crc-doc1
              label: CRC Setup
              href: /cd-crc/crc
        - id: quicklab
          label: quicklab
          links:
            - id: ql-1
              label: Quicklab Setup
              href: /cd-quicklab/quicklab
```
but the website didn't render it, so I might be missing something...@cfchase would you happen to know if there is another way I should be going about this? 
Another issue is to figure out how to link documents from these multiple directories within the remote repo.
