### ISSUE TITLE
include remote git repositories in build

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#9]
ability to include https://github.com/operate-first/continuous-deployment/tree/master/docs in the rendered output.

- white/blacklisting of included files
- add name for repo to sidebar
- add files as navigation to sidebar

**Comment by oindrillac** [comment]
this would allow us to include DS blogs/tutorials from within individual repos.

**Comment by goern** [comment]
we would be happy if we could include our sphinx-generated API doc. 

@saisankargochhayat @harshad16 @fridex

**Comment by cfchase** [comment]
@durandom I'm assuming I reformat and rearrange the Markdown files in the [cd docs](https://github.com/operate-first/continuous-deployment/tree/master/docs) to work with the Gatsby processing?

@goern can you point me in the direction of the sphinx generated docs?  How rigid is the output and format?

**Comment by cfchase** [comment]
> ability to include https://github.com/operate-first/continuous-deployment/tree/master/docs in the rendered output.
>
> * white/blacklisting of included files
- no whitelist is supported by the gatsby-source-filesystem, but you could add each file individually.  It's generally not necessary since it's statically compiled though and wouldn't be included in the built files
- blacklist supported using optional `ignore` field

> * add name for repo to sidebar
> * add files as navigation to sidebar
The `toc.yaml` is merged with other tocs, that way a single docs can have multiple sections.  If you want a group for a subrepo you would just give it a group at the top level.  Links would be underneath.  I'm guessing those links would want to be under a prefix (in this case `cd`), so I included the field `urlPrefix`.  Example below.


```yaml
- name: continuous deployment docs
  dir: continuous-deployment/docs
  ignore:
    - '*.js'
    - '*.exe'
  urlPrefix: cd
  toc: continuous-deployment/docs/toc.yaml
```

```yaml
- id: continuous-deployment
  label: Continuous Deployment
  links:
    - id: versions
      label: Versions
      href: /cd/versions
```
